apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: {{ .Values.gateway.namespace | default "crucible-system" }}
  labels:
    app.kubernetes.io/name: spark-history-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 18080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: spark-history-server
