{{- if and .Values.historyServer.enabled .Values.historyServer.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-history-server
  namespace: {{ .Values.gateway.namespace | default "crucible-system" }}
  labels:
    app.kubernetes.io/name: spark-history-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.historyServer.persistence.storageClass }}
  storageClassName: {{ .Values.historyServer.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.historyServer.persistence.size | default "10Gi" }}
{{- end }}
