{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "crucible.fullname" . }}
  namespace: {{ .Values.gateway.namespace }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "crucible.selectorLabels" . | nindent 6 }}
{{- end }}
