apiVersion: v1
kind: Service
metadata:
  name: {{ include "crucible.fullname" . }}
  namespace: {{ .Values.gateway.namespace }}
  labels:
    {{- include "crucible.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "crucible.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
  type: ClusterIP
