{{ if .Values.platform.deployFetcher }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fetcher-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.platform.ingress.fetcher.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.platform.ingress.fetcher.className }}
  rules:
    {{- if .Values.infra.domains.fetcher }}
    - host: {{ .Values.infra.domains.fetcher }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fetcher-service
                port:
                  number: 80
{{ end }}
