apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestration-hub-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- with .Values.platform.ingress.hub.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.platform.ingress.hub.className }}
  rules:
    {{- if .Values.infra.domains.hub }}
    - host: {{ .Values.infra.domains.hub }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orchestration-hub-service
                port:
                  number: 80
