apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipline-orchestration-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: zipline-ui
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.platform.orchestration.ui.replicas }}
  selector:
    matchLabels:
      app: zipline-ui
  template:
    metadata:
      labels:
        app: zipline-ui
    spec:
      serviceAccountName: {{ .Values.platform.serviceAccount.name }}
      {{- with .Values.platform.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web-ui
          image: "{{ .Values.platform.orchestration.ui.image }}:{{ .Values.platform.version }}"
          imagePullPolicy: Always
          env:
            - name: API_BASE_URL
              value: "http://orchestration-hub-service"
            {{- if .Values.platform.deployFetcher }}
            - name: FETCHER_BASE_URL
              value: "http://fetcher-service"
            {{- end }}
            - name: DB_HOST
              value: {{ .Values.infra.database.host | quote }}
            - name: DB_NAME
              value: {{ .Values.infra.database.name | quote }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: AWS_REGION
              value: "{{ .Values.infra.aws.region }}"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.infra.aws.region }}"
            - name: PUBLIC_ORCH_SERVER_NAME
              value: "{{ .Values.infra.global.customerName }}-zipline-orchestration"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DATABASE_URL
              value: "postgres://$(DB_USERNAME)@{{ .Values.infra.database.host }}/{{ .Values.infra.database.name }}?sslmode=require"
            - name: AWS_EKS_LOG_GROUP
              value: "/aws/eks/{{ .Values.infra.aws.eksClusterName }}/containers"
            - name: AWS_EMR_LOG_GROUP
              value: "/emr/zipline-{{ .Values.infra.global.customerName }}"
            - name: ORCH_CONTAINER_NAME
              value: "orchestration-hub"
            - name: PROMETHEUS_QUERY_ENDPOINT
              value: "{{ .Values.infra.prometheus.queryEndpoint }}"
            - name: PROMETHEUS_NAMESPACE
              value: "{{ .Values.infra.prometheus.namespace }}"
            - name: AUTH_ENABLED
              value: "{{ .Values.platform.auth.enabled }}"
            {{- if .Values.platform.auth.enabled }}
            - name: AUTH_URL
              value: "{{ .Values.platform.auth.url }}"
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: auth-secret
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: AUTH_ALLOWED_HOSTS
              value: "$(POD_IP):{{ .Values.platform.orchestration.ui.port }}"
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: "{{ .Values.platform.auth.googleOauthClientId }}"
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: google-oauth-client-secret
            - name: GITHUB_OAUTH_CLIENT_ID
              value: "{{ .Values.platform.auth.githubOauthClientId }}"
            - name: GITHUB_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: github-oauth-client-secret
            - name: MICROSOFT_ENTRA_TENANT_ID
              value: "{{ .Values.platform.auth.microsoftEntraTenantId }}"
            - name: MICROSOFT_ENTRA_OAUTH_CLIENT_ID
              value: "{{ .Values.platform.auth.microsoftEntraOauthClientId }}"
            - name: MICROSOFT_ENTRA_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: microsoft-entra-oauth-client-secret
            - name: SSO_PROVIDER_ID
              value: "{{ .Values.platform.auth.ssoProviderId }}"
            - name: SSO_DOMAIN
              value: "{{ .Values.platform.auth.ssoDomain }}"
            - name: SSO_ISSUER
              value: "{{ .Values.platform.auth.ssoIssuer }}"
            - name: SSO_CLIENT_ID
              value: "{{ .Values.platform.auth.ssoClientId }}"
            - name: SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: sso-client-secret
            - name: IDP_ROLE_MAPPING
              value: "{{ .Values.platform.auth.idpRoleMapping }}"
            - name: IDP_GROUP_CLAIM
              value: "{{ .Values.platform.auth.idpGroupClaim }}"
            {{- end }}

          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
          {{- toYaml .Values.platform.orchestration.ui.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.platform.orchestration.ui.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.platform.orchestration.ui.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.platform.orchestration.ui.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "db-secret-provider"
---
apiVersion: v1
kind: Service
metadata:
  name: orchestration-ui-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
spec:
  selector:
    app: zipline-ui
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.platform.orchestration.ui.port }}
      protocol: TCP
  type: ClusterIP
