apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-secret-provider
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: password
          key: password
        - objectName: username
          key: username
    {{- if .Values.aws.databricksSpSecretArn }}
    - secretName: databricks-sp-credentials
      type: Opaque
      data:
        - objectName: client_id
          key: client_id
        - objectName: client_secret
          key: client_secret
    {{- end }}
  parameters:
    objects: |
      - objectName: {{ .Values.aws.secretsArn }}
        objectType: secretsmanager
        jmesPath:
          - path: password
            objectAlias: password
          - path: username
            objectAlias: username
      {{- if .Values.aws.databricksSpSecretArn }}
      - objectName: {{ .Values.aws.databricksSpSecretArn }}
        objectType: secretsmanager
        jmesPath:
          - path: client_id
            objectAlias: client_id
          - path: client_secret
            objectAlias: client_secret
      {{- end }}
