{{- if .Values.platform.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.platform.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zipline-orchestration.labels" . | nindent 4 }}
  {{- if .Values.infra.iam.orchestrationIrsaArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.infra.iam.orchestrationIrsaArn | quote }}
  {{- end }}
{{- end }}
