replicaCount: 1

cloudProvider: aws

image:
  repository: 011528299780.dkr.ecr.us-east-1.amazonaws.com/crucible-gateway
  tag: "latest"
  pullPolicy: Always

objectStore:
  bucket: s3://crucible-test-nikhil
  region: us-east-1

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::011528299780:role/crucible-gateway"

sparkDefaults:
  eventLogDir: "s3a://crucible-test-nikhil/spark-events"
  executorCores: 1
  executorMemory: "2Gi"
  driverCores: 1
  driverMemory: "1Gi"
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::011528299780:role/crucible-spark"
  adminConf: {}

flinkDefaults:
  checkpointDir: "s3a://crucible-test-nikhil/flink/checkpoints"
  savepointDir: "s3a://crucible-test-nikhil/flink/savepoints"
  parallelism: 1
  taskSlots: 1
  jmMemory: "1024m"
  jmCPU: 0.5
  tmMemory: "1024m"
  tmCPU: 1

gateway:
  defaultJobNamespace: test-ns-a
  maxJobsPerNamespace: 50

warmPool:
  enabled: false

imagePrepull:
  enabled: false

historyServer:
  image: "011528299780.dkr.ecr.us-east-1.amazonaws.com/spark:4.1-crucible-latest"
  daemonMemory: "1g"
  hybridStoreMemory: "512m"
  maxDiskUsage: "5g"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      memory: "2Gi"
  persistence:
    enabled: false
