cloudProvider: azure

image:
  repository: REGISTRY_NAME.azurecr.io/crucible-gateway
  tag: "0.1.0"
  pullPolicy: IfNotPresent

objectStore:
  bucket: https://STORAGE_ACCOUNT.blob.core.windows.net/crucible

serviceAccount:
  create: true
  annotations:
    azure.workload.identity/client-id: CLIENT_ID

persistence:
  enabled: true
  storageClass: managed-premium
  size: 10Gi

flinkDefaults:
  checkpointDir: "abfss://crucible@STORAGE_ACCOUNT.dfs.core.windows.net/flink/checkpoints"
  savepointDir: "abfss://crucible@STORAGE_ACCOUNT.dfs.core.windows.net/flink/savepoints"
