replicaCount: 1

cloudProvider: azure

image:
  repository: ziplinecanary.azurecr.io/crucible-gateway
  tag: "latest"
  pullPolicy: Always

objectStore:
  bucket: https://ziplineai2.blob.core.windows.net/crucible

serviceAccount:
  create: true
  annotations:
    azure.workload.identity/client-id: "5db0e3c1-eef7-4a78-9a60-6d759615dcf9"

sparkDefaults:
  nvmeEnabled: false
  nvmeSetupImage: "ziplinecanary.azurecr.io/crucible-nvme-setup:latest"
  executorNodeSelector:
    crucible.ai/arch: arm64
  executorTolerations: []
  spotNodeSelector: {}
  eventLogDir: "abfss://crucible@ziplineai2.dfs.core.windows.net/spark-events"
  executorCores: 1
  executorMemory: "1Gi"
  driverCores: 1
  driverMemory: "1Gi"
  serviceAccountAnnotations:
    azure.workload.identity/client-id: "5db0e3c1-eef7-4a78-9a60-6d759615dcf9"
  adminConf:
    "spark.hadoop.fs.azure.account.oauth2.msi.tenant": "48e0cf82-8462-48fe-b995-5accce3156d0"
    "spark.hadoop.fs.azure.account.oauth2.client.id": "5db0e3c1-eef7-4a78-9a60-6d759615dcf9"

flinkDefaults:
  checkpointDir: "abfss://crucible@ziplineai2.dfs.core.windows.net/flink/checkpoints"
  savepointDir: "abfss://crucible@ziplineai2.dfs.core.windows.net/flink/savepoints"
  parallelism: 1
  taskSlots: 1
  jmMemory: "1024m"
  jmCPU: 0.5
  tmMemory: "1024m"
  tmCPU: 1
  adminConf:
    "fs.azure.account.oauth2.msi.tenant": "48e0cf82-8462-48fe-b995-5accce3156d0"
    "fs.azure.account.oauth2.client.id": "5db0e3c1-eef7-4a78-9a60-6d759615dcf9"

gateway:
  defaultJobNamespace: test-ns-a
  maxJobsPerNamespace: 50
  externalBasePath: /api/crucible

ingress:
  enabled: true
  className: nginx-claims-demo-hub
  host: crucible-azure.zipline.ai
  path: /api/crucible
  pathType: Prefix

warmPool:
  enabled: false

imagePrepull:
  enabled: false

historyServer:
  image: "ziplinecanary.azurecr.io/spark:4.1-crucible-latest"
  daemonMemory: "1g"
  hybridStoreMemory: "512m"
  maxDiskUsage: "5g"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      memory: "8Gi"
  persistence:
    enabled: false

rayHistoryServer:
  enabled: true
  image: "ziplinecanary.azurecr.io/ray-historyserver:kuberay-1.6.1-ray-2.55.1-latest"
  collectorImage: "ziplinecanary.azurecr.io/ray-history-collector:kuberay-1.6.1-ray-2.55.1-latest"
  rayImage: "rayproject/ray:2.55.1"
  runtimeClass: "azureblob"
  rootDir: "log"
  env:
    AZURE_STORAGE_AUTH_MODE: "workload_identity"
    AZURE_STORAGE_ACCOUNT_URL: "https://ziplineai2.blob.core.windows.net"
    AZURE_STORAGE_CONTAINER: "crucible"
